### PR TITLE
Add maps support

### PR DESCRIPTION
**Pull request by urbanserj**

### CODE REVIEW

**Comment by urbanserj** [comment]
@hcs42 I added `-mode(compile).` not to make the script faster but to make debugging easier.

Without:

```
./erlang_complete.erl list-functions module
escript: exception error: {function_clause,[{local,simplify_return,[{map,[],[]}]}]}
```

With:

```
./erlang_complete.erl list-functions module
escript: exception error: no function clause matching 
                 erlang_complete_erl__escript__1447__189173__992777:simplify_return({map,
                                                                                     [],
                                                                                     []}) (./erlang_complete.erl, line 315)
  in function  lists:map/2 (lists.erl, line 1237)
  in call from erlang_complete_erl__escript__1447__189173__992777:simplify_return/1 (./erlang_complete.erl, line 331)
  in call from erlang_complete_erl__escript__1447__189173__992777:analyze_function/1 (./erlang_complete.erl, line 304)
  in call from erlang_complete_erl__escript__1447__189173__992777:map_functions/2 (./erlang_complete.erl, line 294)
  in call from erlang_complete_erl__escript__1447__189173__992777:map_functions/2 (./erlang_complete.erl, line 294)
  in call from erlang_complete_erl__escript__1447__189173__992777:module_edoc/1 (./erlang_complete.erl, line 266)
  in call from erlang_complete_erl__escript__1447__189173__992777:run2/1 (./erlang_complete.erl, line 157)
```

Thanks for testing the performance! I will remove this mode.

**Comment by hcs42** [comment]
>  I added -mode(compile). not to make the script faster but to make debugging easier.

Thanks, I didn't know about that! I will also use this trick when debugging :) But probably it's best to use it only for debugging.

**Comment by urbanserj** [comment]
@hcs42 Got it. I wrote simple [example](https://gist.github.com/urbanserj/55030c5a49095190a081). Output of the script for this module is the following: 

```
bar() -> #{}
baz() -> #{atom() => integer()}
corge(Map) -> #{}
foo() -> #{}
quux() -> #{a() => b(), atom() => #{}}
qux() -> b()
```

**Comment by aerosol** [comment]
:+1:

**Comment by hcs42** [comment]
Merged, thanks for the PR.

**Pull request merged**
