### PR TITLE
Add preview, and some other little change

### PR DESCRIPTION
**Pull request by johnzeng**
## Changelog:

- Add function spec to Omni info, so you can get the preview if you want.
- Return `()` instead of `(` if the function doesn't accept any parameter.
- Little improve on local function list, It will provide more results now.

## About the local function list change

Look at the following example:

```
 test(A) ->
    ok.

another_test(A) ->
    ok.
```

In this example, if you list local functions, in the old version, you won't get `test(A)` because its name is not started from the head of that line, so `^\w*` won't match this function and you won't get this function in the return list.

This PR fixed this problem.

### CODE REVIEW

**Comment by johnzeng** [comment]
Add an option to allow a user to don't return the left bracket when you select in the menu. This is useful if the user uses auto-pairs, or when he wanna use the function as a parameter.

Also, add an option to expand function spec like `test/1` to `test(T1) -> term()` in info field.

**Comment by hcs42** [comment]
Thank you. After a first look, I have two questions:

- Does the preview window contain the same information as the preview menu, except for replacing "random:module/1" with "random:module(T1)"? Why is that useful? (I guess it is; I just don't see it :) )
- What does "arbit" mean?

**Comment by johnzeng** [comment]
1, the information is same, the difference is preview menu disappear after selection, but preview window does not
2, that's misspelling, should be arity.

**Comment by hcs42** [comment]
Slowly but surely, I'm making progress. I added a few commits to the [master branch](https://github.com/vim-erlang/vim-erlang-omnicomplete/commits/master):

- [Some comments](https://github.com/vim-erlang/vim-erlang-omnicomplete/commit/f188a10aac2b87be0741df89cc561262cd9feaba) so that it is easier to understand the original code.
- [The first preview commit with a help message added to the user.](https://github.com/vim-erlang/vim-erlang-omnicomplete/commit/8a6ad6585bfb4e5e6bba4951ed5d09998abbaa48) (I don't want users who update the plugin to be surprised by the preview window and not knowing that it is and what to do with it.)
- [Documentation about the commands and options](https://github.com/vim-erlang/vim-erlang-omnicomplete/commit/6e0c913e1d30adda11475c11f72e64257fbccd1b).
- [I added you to the contributor list in the help file as `Zengda <zengda@yunba.io>`](https://github.com/vim-erlang/vim-erlang-omnicomplete/blob/8a6ad6585bfb4e5e6bba4951ed5d09998abbaa48/doc/vim-erlang-omnicomplete.txt#L73). Please let me know if you prefer to appear in a different way.

**Comment by johnzeng** [comment]
I am ok with that. I am closing this PR.

**Comment by hcs42** [comment]
@johnzeng: Thank you for your ideas and for your patience.

I created two commits from the remaining functionality that you introduced in this PR, and I pushed them to master:

* 94f9ddb (#16) Add '()' after zero arity functions
* a1d90f0 (#16) Generate type spec for function where only the arity is known

The only functionality in the PR that I didn't include was the "local function list change". The reason is that even though the current (old) code missed function names that weren't in column 1, the new code missed function names whose parameter list contains patterns. For example completing for `nth` in the `lists` module does not work because `nth` is defined as:

```
nth(1, [H|_]) -> H;
nth(N, [_|T]) when N > 1 ->
```

Also, it is a bad style to write functions that don't begin in column one. If you call completion in a module, that means that you are modifying that module, so have the power to fix the code and make the functions start at column 1.

Regarding the overall development: I made refactorings, a Contributing README section and automatic tests in https://github.com/vim-erlang/vim-erlang. This will help me to help contributors much more efficiently from now on.

**Pull request closed without merging**
